# Generated by Django 5.1.5 on 2025-02-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_orderitem_product_alter_product_collection_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
